services:
  - type: web
    name: bankbounty-backend
    env: node
    region: oregon # Choose your preferred region
    plan: free # or upgrade to starter/standard if needed
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /api
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        value: your-super-secret-jwt-key-change-this-in-production
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: GOOGLE_CLIENT_ID
        value: your-google-client-id
      - key: GOOGLE_CLIENT_SECRET
        value: your-google-client-secret
      - key: FRONTEND_URL
        value: https://your-frontend-domain.com
      - key: DB_HOST
        value: db.xuomcxdchkuvcbwlmigv.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: Kp-&zh9iRRfcqpL
      - key: DB_NAME
        value: postgres

databases:
  - name: bankbounty-postgres
    databaseName: bankbounty
    user: bankbounty_user
    region: oregon # Same region as your web service
    plan: free
